CREATE TABLE USERS(
   ID SERIAL PRIMARY KEY,
   USERNAME VARCHAR(20) NOT NULL UNIQUE,
   PASSWORD VARCHAR(20) NOT NULL,
   FULLNAME VARCHAR(100) NOT NULL
);

SELECT * FROM USERS WHERE LOWER(FULLNAME) LIKE LOWER('%tommy%') OR LIKE LOWER('tommy%') OR LIKE LOWER('%tommy');
